#原稿目录:DIR
source: .

#日记目录:DIR
destination: ./_site

#插件目录
plugins_dir: ./_plugins

#布局目录
layouts_dir: ./_layouts

#安全模式（禁用插件）:BOOL
safe: false

gems:
  - github-pages
  - jekyll-paginate

#转换时强制排除的文件、目录:[DIR, FILE, ...]
exclude:
  - ./app/
  - ./node_modules/
  - ./typeings/

#转换时强制包含的文件、目录:[DIR, FILE, ...]
#include:

#时区:TIMEZONE
#timezone:

#文件编码:ENCODING
encoding: utf-8

#用将来日期发布文章:BOOL
#future:

#生成索引:BOOL
#lsi:

#限制日记数量:NUM
#limit_posts:

#监听主机:HOST
#host: 127.0.0.1

#监听端口:PORT
#port: 4000

#网站根路径:RUL
#baseurl:

#后台模式:BOOL
#detach: true

title: Hyrule
email: wolfired@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
twitter_username: wolfired
github_username:  wolfired

theme: minima

highlighter: rouge

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

user:
 ico_favicon: /assets/site/ico/boo.ico
 css_hightlight: /assets/site/css/rouge.css
 css_custom: /assets/site/css/custom.css
 font_camingo_code_regular: /assets/site/font/CamingoCodeRegular.ttf
 font_camingo_code_bold: /assets/site/font/CamingoCodeBold.ttf
 font_camingo_code_italic: /assets/site/font/CamingoCodeItalic.ttf
 font_camingo_code_bold_italic: /assets/site/font/CamingoCodeBoldItalic.ttf
